#!/bin/bash

# show commands being run
set -x

source /etc/environ.sh
use -e -r qt-4.8.5
use -e -r cmake-3.7.2

# Fail script on error.
set -e

pkgname=connectome-workbench
VERSION=1.2.3
basedir=/apps/share64/debian7
pkginstalldir=${basedir}/${pkgname}
tarinstalldir=${pkginstalldir}/tars
installprefix=${pkginstalldir}/${VERSION}
tarfilebase=workbench-${VERSION}
tarfilename=v${VERSION}.tar.gz
downloaduri=https://github.com/Washington-University/workbench/archive/${tarfilename}
environdir=${basedir}/environ.d
script=$(readlink -f ${0})
installdir=$(dirname ${script})
cpucount=`cat /proc/cpuinfo | grep processor | wc -l`

if [[ ! -d ${pkginstalldir}/tars ]] ; then
    mkdir -p ${pkginstalldir}/tars
fi
cd ${pkginstalldir}/tars

if [[ ! -e ${tarfilename} ]] ; then
    wget ${downloaduri}
fi

rm -rf ${tarfilebase}
tar xvzf ${tarfilename}
cd ${tarfilebase}/src

cmake \
   -D CMAKE_INSTALL_PREFIX=${installprefix} \
   -D CMAKE_BUILD_TYPE=Release \
   .

make -j${cpucount}
make install

if [[ ! -d ${environdir} ]] ; then
    mkdir ${environdir}
fi

cat <<- _END_ > ${environdir}/${pkgname}-${VERSION}
conflict CONNECTOME_WORKBENCH_CHOICE

desc "Connectome Workbench is an open-source visualization and discovery tool used to explore data generated by the Human Connectome Project"

help "http://www.humanconnectome.org/"

version=${VERSION}
location=${pkginstalldir}/\${version}

prepend            PATH \${location}/bin

tags DEVEL
_END_
